openapi: 3.1.0
info:
  title: Drone with FlightPlan
  version: 1.0.0
paths: {}
components:
  schemas:
    Drone:
      properties:
        name:
          type: string
          title: Name
          default: ''
          x_frontend_fieldName: Name
          x_frontend_fieldDescription: This is the Drone Name
          x_frontend_editable: true
          x_frontend_placeholder: Write the Name of your Drone
        description:
          type: string
          title: Description
          default: ''
          x_frontend_fieldName: Description
          x_frontend_fieldDescription: This is the Drone Description
          x_frontend_editable: true
          x_frontend_placeholder: Write short description of your Drone
        flightplan:
          $ref: '#/components/schemas/LineString'
          title: FlightPlan
          default: ''
          x_frontend_fieldName: FlightPlan
          x_frontend_fieldDescription: Here is a route of the Drone FlightPlan
          x_frontend_editable: true
          x_frontend_placeholder: A Route of the coordinates of the FlightPlan
      required:
        - name
      x-frontend-defaultFields:
        - name
        - description
        - flightplan